language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test
    - stage: build
      if: tag IS present
      script: yarn release
    - stage: deploy
      if: tag IS present
      script: yarn docs:build && yarn storybook:build
      deploy:
        - provider: pages
          cleanup: false
          local_dir: docs/.vuepress/dist
          token: $GITHUB_TOKEN
          keep_history: true
          edge: true
          on:
            tags: true
        - provider: surge
          cleanup: false
          project: ./storybook-static/
          domain: vue-snap.surge.sh
          login: $SURGE_LOGIN
          token: $SURGE_TOKEN
          on:
            tags: true

